#端口号
server:
  port: 8088
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


---
spring:
  profiles: development

jdbc:
    driverclassname: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cjylocaldatabase?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root1234
mybatis:
  typealiasespackage: com.springbootdemo.entity
  mapperlocations: classpath*:com/springbootdemo/mapper/*.xml
  configlocation: classpath:/mybatis-config.xml


---
spring:
  profiles: test
---
spring:
  profiles: production